services:
  downly:
    image: bipinmdr07/downly:latest
    container_name: downly
    restart: always
    ports:
      - 5050:5050
    environment:
      - NODE_ENV=production
      - PORT=5050
      - DB_LOCATION=${DB_LOCATION}
      - DOWNLOAD_LOCATION=${DOWNLOAD_LOCATION}
    volumes:
      - ${DB_LOCATION}:/data/db
      - ${DOWNLOAD_LOCATION}:/data/downloads
    labels:
      - caddy=downly.${DOMAIN:-orangepi2.box}
      - caddy.tls=internal
      - caddy.reverse_proxy={{upstreams 5050}}
      - homepage.group=Media
      - homepage.name=downly
      - homepage.icon=mdi-cloud-arrow-down
      - homepage.href=https://downly.${DOMAIN:-orangepi2.box}
