services:
  karakeep:
    image: ghcr.io/karakeep-app/karakeep:release
    container_name: karakeep
    restart: always
    volumes:
      - ${DATA_PATH}/karakeep:/data
    ports:
      - 3004:3000
    environment:
      NEXTAUTH_URL: https://karakeep.${DOMAIN}
      NEXTAUTH_SECRET: ${KARAKEEP_NEXTAUTH_SECRET}
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      # OPENAI_API_KEY: ...

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    labels:
      - traefik.enable=true
      - traefik.http.routers.karakeep.rule=Host(`karakeep.${DOMAIN}`)
      - traefik.http.routers.karakeep.entrypoints=websecure
      - traefik.http.routers.karakeep.tls=true
      - traefik.http.routers.karakeep.tls.certresolver=homelab
      - traefik.http.services.karakeep.loadbalancer.server.port=3000
      - homepage.group=Productivity
      - homepage.name=karakeep
      - homepage.icon=sh-karakeep
      - homepage.href=https://karakeep.${DOMAIN}

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: chrome
    restart: always
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    container_name: meilisearch
    restart: always
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - ${DATA_PATH}/meilisearch:/meili_data
