networks:
  homelab:
    name: homelab
    driver: bridge
  database:
    name: database
    driver: bridge

services:
  # Traefik
  traefik:
    extends:
      file: ./services/traefik/traefik.yml
      service: traefik
    networks:
      - homelab

  # Adguard
  adguardhome:
    extends:
      file: ./services/adguardhome/adguardhome.yml
      service: adguardhome
    volumes:
      - ${DEFAULT_DATA_PATH}/adguardhome/work:/opt/adguardhome/work
      - ${DEFAULT_CONFIG_PATH}/adguardhome/conf:/opt/adguardhome/conf
    networks:
      - homelab

  # DynamoDB
  dynamodb:
    extends:
      file: ./services/dynamodb/dynamodb.yml
      service: dynamodb
    volumes:
      - ${DEFAULT_DATA_PATH}/dynamodb/:/home/dynamodblocal/data
    networks:
      - database
  
  # DynamoDB Dashboard
  dynamodb-dashboard:
    extends:
      file: ./services/dynamodb-dashboard/dynamodb-dashboard.yml
      service: dynamodb-dashboard
    networks:
      - homelab
      - database
    depends_on:
      - dynamodb

  # Jellyfin
  jellyfin:
    extends:
      file: ./services/jellyfin/jellyfin.yml
      service: jellyfin
    volumes:
      - ${JELLYFIN_MEDIA_PATH}:/media
      - ${DEFAULT_CONFIG_PATH}/jellyfin/config:/config
      - ${DEFAULT_CACHE_PATH}/jellyfin/cache:/cache
    # devices:
    #   - /dev/dri:/dev/dri # For hardware acceleration (Intel/AMD)
    networks:
      - homelab