networks:
  default:
    name: homelab
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

  database:
    name: database
    driver: bridge

volumes:
  model-cache:

  shared_data:
    driver: local
    driver_opts:
      type: none
      device: $SHARED_DATA_PATH
      o: bind

services:
  # Twingate connector
  twingate-connector:
    extends:
      file: ./services/twingate/twingate-connector.yml
      service: twingate-connector

  # Step CA
  stepca:
    extends:
      file: ./services/traefik/traefik.yml
      service: stepca

  # Traefik
  traefik:
    extends:
      file: ./services/traefik/traefik.yml
      service: traefik

  # Adguard
  adguardhome:
    extends:
      file: ./services/adguardhome/adguardhome.yml
      service: adguardhome

  # DynamoDB
  dynamodb:
    extends:
      file: ./services/dynamodb/dynamodb.yml
      service: dynamodb
  
  # DynamoDB Dashboard
  dynamodb-dashboard:
    extends:
      file: ./services/dynamodb-dashboard/dynamodb-dashboard.yml
      service: dynamodb-dashboard

  # Jellyfin
  jellyfin:
    extends:
      file: ./services/jellyfin/jellyfin.yml
      service: jellyfin

  # Syncthing
  syncthing:
    extends:
      file: ./services/syncthing/syncthing.yml
      service: syncthing

  # Portainer
  portainer:
    extends:
      file: ./services/portainer/portainer.yml
      service: portainer

  # n8n
  n8n:
    extends:
      file: ./services/n8n/n8n.yml
      service: n8n

  # redis
  redis:
    extends:
      file: ./services/redis/redis.yml
      service: redis

  # redisinsight
  redisinsight:
    extends:
      file: ./services/redis/redis.yml
      service: redisinsight

  # postgres
  postgres:
    extends:
      file: ./services/postgres/postgres.yml
      service: postgres

  # pgweb
  pgweb:
    extends:
      file: ./services/postgres/postgres.yml
      service: pgweb

  # MinIO
  minio:
    extends:
      file: ./services/minio/minio.yml
      service: minio

  # Passbolt
  passbolt:
    extends:
      file: ./services/passbolt/passbolt.yml
      service: passbolt

  # Nextcloud
  nextcloud:
    extends:
      file: ./services/nextcloud/nextcloud.yml
      service: nextcloud

  # Nextcloud cron
  nextcloud-cron:
    extends:
      file: ./services/nextcloud/nextcloud.yml
      service: nextcloud-cron

  # Immich
  immich-server:
    extends:
      file: ./services/immich/immich.yml
      service: immich-server

  immich-machine-learning:
    extends:
      file: ./services/immich/immich.yml
      service: immich-machine-learning

  # Downly
  downly:
    extends:
      file: ./services/downly/downly.yml
      service: downly

  # Homepage
  homepage:
    extends:
      file: ./services/homepage/homepage.yml
      service: homepage

  # Cron Master
  cronmaster:
    extends:
      file: ./services/cronmaster/cronmaster.yml
      service: cronmaster
