networks:
  default:
    name: homelab
    driver: bridge
  database:
    name: database
    driver: bridge

services:
  # Twingate connector
  twingate-connector:
    extends:
      file: ./services/twingate/twingate-connector.yml
      service: twingate-connector

  # Traefik
  traefik:
    extends:
      file: ./services/traefik/traefik.yml
      service: traefik

  # Adguard
  adguardhome:
    extends:
      file: ./services/adguardhome/adguardhome.yml
      service: adguardhome

  # DynamoDB
  dynamodb:
    extends:
      file: ./services/dynamodb/dynamodb.yml
      service: dynamodb
  
  # DynamoDB Dashboard
  dynamodb-dashboard:
    extends:
      file: ./services/dynamodb-dashboard/dynamodb-dashboard.yml
      service: dynamodb-dashboard

  # Jellyfin
  jellyfin:
    extends:
      file: ./services/jellyfin/jellyfin.yml
      service: jellyfin

  # Syncthing
  syncthing:
    extends:
      file: ./services/syncthing/syncthing.yml
      service: syncthing

  # Portainer
  portainer:
    extends:
      file: ./services/portainer/portainer.yml
      service: portainer

  # n8n
  n8n:
    extends:
      file: ./services/n8n/n8n.yml
      service: n8n

  # redis
  redis:
    extends:
      file: ./services/redis/redis.yml
      service: redis

  # redisinsight
  redisinsight:
    extends:
      file: ./services/redis/redis.yml
      service: redisinsight

  # postgres
  postgres:
    extends:
      file: ./services/postgres/postgres.yml
      service: postgres

  # pgadmin4
  pgadmin:
    extends:
      file: ./services/postgres/postgres.yml
      service: pgadmin

  # MinIO
  minio:
    extends:
      file: ./services/minio/minio.yml
      service: minio

  # Passbolt
  passbolt:
    extends:
      file: ./services/passbolt/passbolt.yml
      service: passbolt