services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ${DATA_PATH}/dynamodb/:/home/dynamodblocal/data
    networks:
      - database
    labels:
      - traefik.enable=true
      - traefik.http.routers.dynamodb.rule=Host(`dynamodb.${DOMAIN:-orangepi2.box}`)
      - traefik.http.routers.dynamodb.entrypoints=websecure
      - traefik.http.routers.dynamodb.tls=true
      - traefik.http.routers.dynamodb.tls.certresolver=homelab
      - traefik.http.services.dynamodb.loadbalancer.server.port=8000
      - homepage.group=Database
      - homepage.name=dynamodb
      - homepage.icon=mdi-database
      - homepage.href=https://dynamodb.${DOMAIN:-orangepi2.box}
