services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - ${DATA_PATH}/dynamodb/:/home/dynamodblocal/data
    networks:
      - database
    labels:
      - caddy=dynamodb.${DOMAIN:-orangepi2.box}
      - caddy.tls=internal
      - caddy.reverse_proxy={{upstreams 8000}}
      - homepage.group=Database
      - homepage.name=dynamodb
      - homepage.icon=mdi-database
      - homepage.href=https://dynamodb.${DOMAIN:-orangepi2.box}
