services:
  passbolt:
    image: passbolt/passbolt:latest-ce-non-root
    container_name: passbolt
    restart: always
    environment:
      - APP_FULL_BASE_URL=http://passbolt.${DOMAIN:-orangepi2.box}
      - DATASOURCES_DEFAULT_DRIVER=Cake\Database\Driver\Postgres
      - DATASOURCES_DEFAULT_ENCODING=utf8
      - DATASOURCES_DEFAULT_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/passbolt?schema=public
      - EMAIL_TRANSPORT_DEFAULT_HOST=smtp.gmail.com
      - EMAIL_TRANSPORT_DEFAULT_PORT=587
      - EMAIL_TRANSPORT_DEFAULT_TLS=true
      - EMAIL_TRANSPORT_DEFAULT_USERNAME=${EMAIL_FROM}
      - EMAIL_DEFAULT_FROM=${EMAIL_FROM}
      - EMAIL_TRANSPORT_DEFAULT_PASSWORD=${EMAIL_PASSWORD}
      - TZ=${TZ}
    ports:
      - 8085:8080
    volumes:
      - ${DATA_PATH}/passbolt:/var/www/passbolt
    depends_on:
      - postgres
    networks:
      - database
      - default
    command: >
      /bin/sh -c "
        /usr/bin/wait-for.sh -t 0 postgres:5432 -- true;

        (sleep 30; /usr/share/php/passbolt/bin/cake passbolt register_user -u ${EMAIL_FROM} -f ${PASSBOLT_ADMIN_FIRST_NAME} -l ${PASSBOLT_ADMIN_LAST_NAME} -r admin || true) &

        /docker-entrypoint.sh
      "
    labels:
      - traefik.enable=true
      - traefik.http.routers.passbolt.rule=Host(`passbolt.${DOMAIN:-orangepi2.box}`)
      - traefik.http.routers.passbolt.entrypoints=websecure
      - traefik.http.routers.passbolt.tls=true
      - traefik.http.routers.passbolt.tls.certresolver=homelab
      - traefik.http.services.passbolt.loadbalancer.server.port=8080
      - traefik.docker.network=homelab
      - homepage.group=Productivity
      - homepage.name=passbolt
      - homepage.icon=passbolt
      - homepage.href=https://passbolt.${DOMAIN:-orangepi2.box}
    
