services:
  cronmaster:
    image: ghcr.io/fccview/cronmaster:latest
    container_name: cronmaster
    user: "root"
    init: true
    restart: always
    ports:
      - "4404:3000"
    environment:
      - NODE_ENV=production
      - DOCKER=true
      - HOST_PROJECT_DIR=${DATA_PATH}/cronmaster
      - NEXT_PUBLIC_CLOCK_UPDATE_INTERVAL=30000
      - HOST_CRONTAB_USER=root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}/cronmaster/scripts:/app/scripts
      - ${DATA_PATH}/cronmaster/data:/app/data
      - ${DATA_PATH}/cronmaster/snippets:/app/snippets
      - shared_data:/mnt/shared
    pid: "host"
    privileged: true
    labels:
      - caddy=cronmaster.${DOMAIN:-orangepi2.box}
      - caddy.tls=internal
      - caddy.reverse_proxy={{upstreams 3000}}
      - homepage.group=Productivity
      - homepage.name=Cron Master
      - homepage.icon=sh-cr-nmaster
      - homepage.href=https://cronmaster.${DOMAIN:-orangepi2.box}
