services:
  postgres:
    image: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvector0.8.0-pgvectors0.2.1
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH}/postgres/:/var/lib/postgresql/data
      - ./custom-scripts/:/custom-scripts # Mount custom scripts directory
    environment:
      POSTGRES_DB: postgres
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    networks:
      - database
      - default
    command: >
      sh -c "
        docker-entrypoint.sh postgres -c shared_preload_libraries=vchord &
        PG_PID=$$! &&
        until pg_isready -U ${DB_USER}; do sleep 2; done &&
        echo 'PostgreSQL is ready. Running SQL scripts...' &&
        for script in /custom-scripts/*.sql; do
          if [ -f \"$$script\" ]; then
            echo \"Executing $$script\" &&
            psql -U ${DB_USER} -d postgres -f \"$$script\" || echo \"Script $$script completed (may have expected errors)\"
          fi
        done &&
        echo 'All scripts executed.' &&
        wait $$PG_PID
      "
    labels:
      - traefik.enable=true
      - traefik.http.routers.postgres.rule=Host(`postgres.${DOMAIN:-orangepi2.box}`)
      - traefik.http.routers.postgres.entrypoints=websecure
      - traefik.http.routers.postgres.tls=true
      - traefik.http.routers.postgres.tls.certresolver=homelab
      - traefik.http.services.postgres.loadbalancer.server.port=5432
      - traefik.docker.network=homelab
      - homepage.group=Database
      - homepage.name=postgres
      - homepage.icon=si-postgresql
      - homepage.href=https://postgres.${DOMAIN:-orangepi2.box}

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    restart: always
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    networks:
      - default
      - database
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgweb.rule=Host(`pgweb.${DOMAIN:-orangepi2.box}`)
      - traefik.http.routers.pgweb.entrypoints=websecure
      - traefik.http.routers.pgweb.tls=true
      - traefik.http.routers.pgweb.tls.certresolver=homelab
      - traefik.http.services.pgweb.loadbalancer.server.port=8081
      - traefik.docker.network=homelab
      - homepage.group=Data
      - homepage.name=pgweb
      - homepage.icon=si-postgresql
      - homepage.href=https://pgweb.${DOMAIN:-orangepi2.box}
