services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH}/postgres/:/var/lib/postgresql/data
      - ./custom-scripts/:/custom-scripts # Mount custom scripts directory
    environment:
      POSTGRES_DB: postgres
      PGPASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    networks:
      - database
    command: >
      sh -c "
        docker-entrypoint.sh postgres &
        PG_PID=$$! &&
        until pg_isready -U ${DB_USER}; do sleep 2; done &&
        echo 'PostgreSQL is ready. Running SQL scripts...' &&
        for script in /custom-scripts/*.sql; do
          if [ -f \"$$script\" ]; then
            echo \"Executing $$script\" &&
            psql -U ${DB_USER} -d postgres -f \"$$script\" || echo \"Script $$script completed (may have expected errors)\"
          fi
        done &&
        echo 'All scripts executed.' &&
        wait $$PG_PID
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - default
      - database
    depends_on:
      - postgres
    labels:
    - traefik.enable=true
    - traefik.http.routers.pgadmin.rule=Host(`pgadmin.${DOMAIN:-orangepi2.box}`)
    - traefik.http.routers.pgadmin.entrypoints=web
    - traefik.http.services.pgladmin.loadbalancer.server.port=80
    - traefik.docker.network=homelab
