services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9002:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${DATA_PATH}/portainer/:/data
    environment:
      - TZ=${TZ}
    labels:
      - caddy=portainer.${DOMAIN:-orangepi2.box}
      - caddy.tls=internal
      - caddy.reverse_proxy={{upstreams 9000}}
      - homepage.group=Management
      - homepage.name=portainer
      - homepage.icon=si-portainer
      - homepage.href=https://portainer.${DOMAIN:-orangepi2.box}
      - homepage.widget.type=portainer
      - homepage.widget.url=http://portainer:9000
      - homepage.widget.key=${PORTAINER_API_KEY}
      - homepage.widget.env=3
