services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9002:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ${DATA_PATH}/portainer/:/data
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=HOST(`portainer.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.portainer.entrypoints=web"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "homepage.group=Management"
      - "homepage.name=portainer"
      - "homepage.icon=si-portainer"
      - "homepage.href=http://portainer.${DOMAIN:-orangepi2.box}"
      - "homepage.widget.type=portainer"
      - "homepage.widget.url=http://portainer.${DOMAIN:-orangepi2.box}"
      - "homepage.widget.key=${PORTAINER_API_KEY}"
      - "homepage.widget.env=3"