services:
  nextcloud:
    image: nextcloud:28-apache
    container_name: nextcloud
    restart: always
    ports:
      - 8083:80
    volumes:
      - ${DATA_PATH}/nextcloud:/var/www/html
      - ${CONFIG_PATH}/nextcloud:/var/www/html/config
      - ${DATA_PATH}/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${DATA_PATH}/nextcloud/themes:/var/www/html/themes
      - ${DATA_PATH}/nextcloud/data:/var/www/html/data
      # Mount external storage if needed
      # - /mnt/external-drive:/external:rw
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - TZ=${TZ}
      - REDIS_HOST=redis
      # - REDIS_HOST_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - database
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=homelab"
