services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8083:80
    volumes:
      - ${DATA_PATH}/nextcloud:/var/www/html
      - ${CONFIG_PATH}/nextcloud:/var/www/html/config
      - ${DATA_PATH}/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${DATA_PATH}/nextcloud/themes:/var/www/html/themes
      - ${DATA_PATH}/nextcloud/data:/var/www/html/data
      - shared_data:/mnt/shared
      # Custom PHP limits so WebDAV uploads (e.g. iOS app) don’t get 0 bytes read
      - ./php-uploads.ini:/usr/local/etc/php/conf.d/99-uploads.ini:ro
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - TZ=${TZ}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Behind Caddy: same host/URL everywhere so Nextcloud doesn’t 400 on redirects
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=nextcloud.${DOMAIN:-orangepi2.box}
      - OVERWRITECLIURL=https://nextcloud.${DOMAIN:-orangepi2.box}
      # Trust Caddy (homelab subnet); avoids “reverse proxy header configuration incorrect” / 400
      - TRUSTED_PROXIES=172.20.0.0/16
    depends_on:
      - postgres
      - redis
    networks:
      - database
      - default
    labels:
      - caddy=nextcloud.${DOMAIN:-orangepi2.box}
      - caddy.tls=internal
      # Allow large request bodies and long timeouts so WebDAV PUT uploads (e.g. iOS) don’t end up as 0 bytes
      - caddy.request_body.max_size=10GB
      - caddy.reverse_proxy={{upstreams 80}}
      - homepage.group=Productivity
      - homepage.name=nextcloud
      - homepage.icon=si-nextcloud
      - homepage.href=https://nextcloud.${DOMAIN:-orangepi2.box}
      - homepage.widget.type=nextcloud
      - homepage.widget.url=http://nextcloud
      - homepage.widget.username=${NEXTCLOUD_ADMIN_USER}
      - homepage.widget.password=${NEXTCLOUD_ADMIN_PASSWORD}

  nextcloud-cron:
    image: nextcloud
    container_name: nextcloud-cron
    volumes:
      - ${DATA_PATH}/nextcloud:/var/www/html
      - ${CONFIG_PATH}/nextcloud:/var/www/html/config
      - ${DATA_PATH}/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${DATA_PATH}/nextcloud/themes:/var/www/html/themes
      - ${DATA_PATH}/nextcloud/data:/var/www/html/data
      - shared_data:/mnt/shared
    entrypoint: /cron.sh
    depends_on:
      - nextcloud
    networks:
      - database
