services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8083:80
    volumes:
      - ${DATA_PATH}/nextcloud:/var/www/html
      - ${CONFIG_PATH}/nextcloud:/var/www/html/config
      - ${DATA_PATH}/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${DATA_PATH}/nextcloud/themes:/var/www/html/themes
      - ${DATA_PATH}/nextcloud/data:/var/www/html/data
      - shared_data:/mnt/shared
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - TZ=${TZ}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - database
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.nextcloud.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.docker.network=homelab"
      - "homepage.group=Productivity"
      - "homepage.name=nextcloud"
      - "homepage.icon=si-nextcloud"
      - "homepage.href=http://nextcloud.${DOMAIN:-orangepi2.box}"
      - "homepage.widget.type=nextcloud"
      - "homepage.widget.url=http://nextcloud"
      - "homepage.widget.username=${NEXTCLOUD_ADMIN_USER}"
      - "homepage.widget.password=${NEXTCLOUD_ADMIN_PASSWORD}"
