services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"   # HTTP
    volumes:
      - ${CONFIG_PATH}/jellyfin:/config
      - ${CACHE_PATH}/jellyfin:/cache
      - shared_data:/mnt/shared
    environment:
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://jellyfin.${DOMAIN:-orangepi2.box}
    devices:
      - /dev/dri:/dev/dri # For hardware acceleration (Intel/AMD)
    labels:
      - caddy=jellyfin.${DOMAIN:-orangepi2.box}
      - caddy.tls=internal
      - caddy.reverse_proxy={{upstreams 8096}}
      - homepage.group=Media
      - homepage.name=jellyfin
      - homepage.icon=si-jellyfin
      - homepage.href=https://jellyfin.${DOMAIN:-orangepi2.box}
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true
      - homepage.widget.enableUser=true
      - homepage.widget.showEpisodeNumber=true
