services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    ports:
      - "8096:8096"   # HTTP
    volumes:
      - ${JELLYFIN_MEDIA_PATH}:/media
      - ${CONFIG_PATH}/jellyfin/config:/config
      - ${CACHE_PATH}/jellyfin/cache:/cache
    environment:
      - TZ=${TZ}
    # devices:
    #   - /dev/dri:/dev/dri # For hardware acceleration (Intel/AMD)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
