services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - 9009:9000 # Minio API port
      - 9001:9001 # minio console port
    volumes:
      - ${MINIO_DATA_PATH}/:/data
    environment:
      - PUID=1000
      - PGID=1000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TZ}
    command: server /data --console-address ":9001" # Start Minio server with console
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`minio.${DOMAIN:-orangepi2.box}`)
      - traefik.http.routers.minio.entrypoints=websecure
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.certresolver=homelab
      - traefik.http.services.minio.loadbalancer.server.port=9001
      - homepage.group=Storage
      - homepage.name=minio
      - homepage.icon=si-minio
      - homepage.href=https://minio.${DOMAIN:-orangepi2.box}
