services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - 9000:9000 # Minio API port
      - 9001:9001 # minio console port
    volumes:
      - ${DATA_PATH}/minio/:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - TZ=${TZ}
    command: server /data --console-address ":9001" # Start Minio server with console
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.services.minio.loadbalancer.server.port=9001"
      - "homepage.group=Storage"
      - "homepage.name=minio"
      - "homepage.icon=si-minio"
      - "homepage.href=http://minio.${DOMAIN:-orangepi2.box}"
