services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: always
    ports:
      - "53:53/tcp"     # DNS over TCP
      - "53:53/udp"     # DNS over UDP
      - "67:67/udp"     # DHCP server (optional)
      - "68:68/udp"     # DHCP server (optional)
      - "443:443/tcp"
      - "443:443/udp"
      - "8888:8888"
      - "3000:3000"     # Web interface
      - "853:853/tcp"   # DNS over TLS
      - "784:784/udp"   # DNS over QUIC
      - "8853:8853/udp" # DNS over QUIC (alternative port)
      - "5443:5443/tcp" # DNSCrypt
      - "5443:5443/udp" # DNSCrypt
    volumes:
    - ${DATA_PATH}/adguardhome/work:/opt/adguardhome/work
    - ${CONFIG_PATH}/adguardhome:/opt/adguardhome/conf
    environment:
      - AGH_HTTP_BIND=0.0.0.0:8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls=true"
      - "traefik.http.routers.adguard.tls.certresolver=homelab"
      - "traefik.http.services.adguard.loadbalancer.server.url=http://192.168.69.69:8888"
      - "traefik.docker.network=homelab"
      - "homepage.group=Network"
      - "homepage.name=adguard"
      - "homepage.icon=adguard-home"
      - "homepage.href=https://adguard.${DOMAIN:-orangepi2.box}"
      - "homepage.widget.type=adguard"
      - "homepage.widget.url=http://192.168.69.69:8888"
      - "homepage.widget.username=${ADGUARD_USERNAME}"
      - "homepage.widget.password=${ADGUARD_PASSWORD}"
    network_mode: "host" # put for having static ip i.e. of host machine.
#   networks:
#     default:
#       ipv4_address: 172.20.0.2
