services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: always
    ports:
      - "53:53/tcp"     # DNS over TCP
      - "53:53/udp"     # DNS over UDP
      - "67:67/udp"     # DHCP server (optional)
      - "68:68/udp"     # DHCP server (optional)
      - "8090:80"   # HTTP
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000"     # Web interface (avoiding conflict with Postiz)
      - "853:853/tcp"   # DNS over TLS
      - "784:784/udp"   # DNS over QUIC
      - "8853:8853/udp" # DNS over QUIC (alternative port)
      - "5443:5443/tcp" # DNSCrypt
      - "5443:5443/udp" # DNSCrypt
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguardhome.${DOMAIN:-orangepi2.box}`)"
      - "traefik.http.routers.adguard.entrypoints=web"